###
POST http://localhost:5000/todo HTTP/1.1
Content-Type: application/json

{
    "nombre": "Paracetamol",
    "descripcion": "Medicamento para aliviar dolor y fiebre",
    "precio": 15.5,
    "stock": 100,
    "categoria": "Medicamentos",
    "imagen": "paracetamol.jpg"
}

###
GET http://localhost:5000/todo HTTP/1.1

###
GET http://localhost:5000/todo/----------- HTTP/1.1

###
PUT http://localhost:5000/todo/------------- HTTP/1.1
Content-Type: application/json

{
    "nombre": "Paracetamol Extra",
    "precio": 18,
    "stock": 80
}

###
DELETE http://localhost:5000/todo/ID_DEL_PRODUCTO HTTP/1.1